# Numpy (Numerical Python)

Numpy es una biblioteca de Python que se utiliza para realizar cálculos numéricos de manera eficiente. Proporciona estructuras de datos, como arreglos multidimensionales, y funciones para operar con ellos.

Cual es la importancia de Numpy:
- **Eficiencia**: Numpy está optimizado para realizar operaciones matemáticas de manera rápida y eficiente.
- **Facilidad de uso**: Proporciona una sintaxis sencilla para trabajar con arreglos y matrices.
- **Compatibilidad**: Muchas otras bibliotecas de Python, como Pandas y SciPy, dependen de Numpy para sus operaciones numéricas.

librerías que se basan en numpy:
- Pandas
- SciPy
- Matplotlib
- Scikit-learn  


## Instalación
Para instalar Numpy, puedes usar pip. Abre tu terminal y ejecuta el siguiente comando:
```bash
pip install numpy
```
## Importación
Para usar Numpy en tu código, primero debes importarlo. La convención común es importarlo como `np`:
```python
import numpy as np
```
## Creación de arreglos
Puedes crear arreglos de Numpy utilizando la función `np.array()`:
```python
# Crear un arreglo unidimensional
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1) # Salida: [1 2 3 4 5]

# Crear un arreglo bidimensional
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2) # Salida: [[1 2 3]
             #          [4 5 6]]
```
## Operaciones básicas
Numpy permite realizar operaciones matemáticas de manera eficiente:
```python
# Suma de arreglos
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
suma = a + b
print(suma) # Salida: [5 7 9]

# Resta de arreglos
resta = a - b
print(resta) # Salida: [-3 -3 -3]

# Multiplicación elemento a elemento
multiplicacion = a * b
print(multiplicacion) # Salida: [ 4 10 18]

# División elemento a elemento
division = a / b
print(division) # Salida: [0.25 0.4  0.5 ]

# Producto escalar
producto = a * b
print(producto) # Salida: [ 4 10 18]
```
## Funciones útiles
Numpy ofrece muchas funciones útiles para trabajar con arreglos:
```python
# Función para calcular la media
media = np.mean(arr1)
print(media) # Salida: 3.0

# Función para calcular la desviación estándar
desviacion = np.std(arr1)
print(desviacion) # Salida: 1.4142135623730951
```
### Indexación y segmentación
Puedes acceder a elementos específicos de un arreglo utilizando índices:
```python
# Acceder al primer elemento
print(arr1[0]) # Salida: 1
# Acceder a una fila específica en un arreglo bidimensional
print(arr2[1]) # Salida: [4 5 6]
# Acceder a un elemento específico en un arreglo bidimensional
print(arr2[0, 1]) # Salida: 2
```
### Filtrar (indexación booleana)
La indexación booleana te permite filtrar elementos de un arreglo según condiciones específicas. Por ejemplo:
```python
# Filtrar elementos mayores que 2
filtro = arr1 > 2
print(filtro) # Salida: [False False  True  True  True]
print(arr1[filtro]) # Salida: [3 4 5]
```

### Slicing
El slicing en Numpy te permite extraer subarreglos de un arreglo existente utilizando la notación de índices. La sintaxis básica para el slicing es `arr[inicio:fin:paso]`, donde `inicio` es el índice inicial, `fin` es el índice final (exclusivo) y `paso` es el intervalo entre los índices seleccionados. 

Por ejemplo:
```python
# Crear un arreglo
arr = np.array([10, 20, 30, 40, 50, 60])
# Extraer un subarreglo desde el índice 1 hasta el índice 4
subarr = arr[1:4]
print(subarr) # Salida: [20 30 40]
# Extraer elementos con un paso de 2
subarr_paso = arr[::2]
print(subarr_paso) # Salida: [10 30 50]
```

```python
vector = np.arange(30,300)
print(vector[10:50:5]) # realiza un slicing desde el índice 10 hasta el 50 con un paso de 5
# Salida: [ 40  65  90 115 140 165 190 215]
```


## Tensores en Numpy
Los tensores son una generalización de los arreglos multidimensionales. En Numpy, los tensores se representan como arreglos con más de dos dimensiones. Puedes crear tensores de la siguiente manera:
```python
# Crear un tensor tridimensional
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor)
# Salida:
# [[[1 2]
#   [3 4]]
#  [[5 6]
#   [7 8]]]
```
Puedes acceder a los elementos de un tensor utilizando índices múltiples:
```python
# Acceder a un elemento específico en el tensor
elemento = tensor[1, 0, 1]
print(elemento) # Salida: 6
```
Los tensores son útiles en diversas aplicaciones, como el aprendizaje automático y la computación científica, donde se manejan datos con múltiples dimensiones. Numpy facilita la manipulación y operación con tensores, permitiendo realizar cálculos complejos de manera eficiente.
```python
## Operación con tensores
tensor_a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor_b = np.array([[[9, 8], [7, 6]], [[5, 4], [3, 2]]])
suma_tensores = tensor_a + tensor_b
print(suma_tensores)
# Salida:
# [[[10 10]
#   [10 10]]
#  [[10 10]
#   [10 10]]]
```
